### PR TITLE
Support Dynamic Payload Data and True Synchronous Commands

### PR DESCRIPTION
**Pull request by Teagan42**
Dynamic Payload:
- This allows for commands to be sent to devices (fan speed, thermostat control, etc.)
- Kept the `level` argument to allow for backwards compatibility

True Synchronous Commands:
- Insteon Hubs process commands synchronously, 0.4s is not always enough time when many commands are sent at once
- Poll the command status until the status is no longer pending

### CODE REVIEW

**Comment by FreekingDean** [comment]
Hi! I have no Idea why this wasn't ever sent to my email! I feel awful!!!

**Comment by FreekingDean** [comment]
Everything here looks awesome!

Did you happen to test this with home-assistant? (Not that it should be just a question)

**Comment by Teagan42** [comment]
Yes it was tested in home-assistant!

I actually have another improvement to make on this library - allow custom end points so you don't have to go through the cloud every request. I'll make a PR on that later, haven't touched the project in a bit.

**Comment by Teagan42** [comment]
Damnit, I committed to wrong branch. Let me fix those tomorrow.

**Comment by Teagan42** [comment]
Added the custom endpoint for LAN only communication.

**Comment by FreekingDean** [comment]
Awesome! Let me merge this update the version and ill push to pypi 😄

**Pull request merged**
